<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="card text-center">
                            <div class="card-body">
                                <h2 class="card-title">Admin</h2>
                                <p class="card-text">Vous êtes actuellement sur la partie administration du site.</p>
                                <div class="d-flex justify-content-center">
                                    <img src="../view/asset/images/logo.png" class="img-fluid">
                                </div>
                                <div class="row">
                                    <div class="col-lg-8 offset-lg-2 mb-1">
                                        <img src="../view/asset/images/ecole.webp" alt="Bureau One2Learn"
                                            class="img-fluid rounded">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>




        </div>
    </div><!-- end content-page title -->
</div> <!-- content -->





<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 text-center">
                2022 - 2023 &copy; Parent_Eleve <a href="">Dessaint-Arnaud</a>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

</div>
<!-- Vendor js -->
<script src="assets/js/vendor.min.js"></script>

<!-- KNOB JS -->
<script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
<!-- Chart JS -->
<script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

<!-- Jvector map -->
<script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
<script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>

<!-- Datatable js -->
<script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
<script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
<script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
<script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

<!-- Dashboard Init JS -->
<script src="assets/js/pages/dashboard.init.js"></script>

<!-- App js -->
<script src="assets/js/app.min.js"></script>