<div class="card">
    
        <div class="row no-gutters border border-secondary">
            <div class="col-md-4">
                <img src="<?php echo $article['image'] ?>" class="card-img" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">
                        <?php echo $article['titre'] ?>
                    </h5>
                    <p class="card-text">
                        <?php echo $article['paragraphe'] ?>
                    </p>
                </div>
            </div>
        </div>
    
</div>

<!-- footer -->