<div class="card">
    <?php foreach ($listearticle as $La) { ?>
        <div class="row mb-5 border border-secondary">
            <div class="col-md-4">
                <img src="<?php echo $La['image'] ?>" class="card-img" alt="..." style="width:25rem">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">
                        <?php echo $La['titre'] ?>
                    </h5>
                    <p class="card-text">
                        <?php echo $La['paragraphe_abrege'] ?>
                    </p>
                </div>
                <div class="card-footer">
                        <a href="index.php?action=article&id=<?= $La['id']; ?>" class="btn btn-primary">En savoir plus</a>
                    </div>
            </div>
        </div>
    <?php } ?>
</div>

<!-- footer -->