    <section class="offcanvas offcanvas-end" id="userTools">
        <div class="offcanvas-header">
            <h2 class="offcanvas-title">Se connecter</h2>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
        </div>
        <div class="offcanvas-body">
            <form>
                <div class="mb-3">
                    <label for="username" class="form-label">Nom d'utilisateur</label>
                    <input type="text" class="form-control" name="username" id="username">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Mot de passe</label>
                    <input type="password" class="form-control" name="password" id="password">
                </div>
                <div class="form-check form-switch mb-3">
                    <input class="form-check-input" type="checkbox" id="rememberMe" />
                    <label class="form-check-label" for="rememberMe">Se souvenir de moi</label>
                </div>
                <button class="btn btn-primary">Se connecter</button>
            </form>
        </div>
    </section>
    <div class="container-fluid my-3">
        <section class="row gy-3">
            <div class="col-12 col-md-9">
                <!--Begin Breadcrumb-->
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.php">Accueil</a></li>
                        <li class="breadcrumb-item">Blog</li>
                    </ol>
                </nav>
                <!--End Breadcrumb-->
                <!--Begin Pagination-->
                <nav>
                    <ul class="pagination justify-content-center">
                        <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
                        <li class="page-item active"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                    </ul>
                </nav>
                <!--End Pagination-->
                <div class="list-group list-group-flush my-3">
                    <article class="list-group-item">
                        <div class="row">
                            <figure class="col-12 col-md-4 d-none d-md-block">
                                <img src="./view/asset/images/arbre.jpg" alt="Arbre" class="img-fluid img-thumbnail">
                            </figure>
                            <div class="col-12 col-md-8">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat a qui hic nostrum sequi. Nulla quia nesciunt adipisci autem eum. Omnis hic praesentium recusandae. Non saepe vero totam mollitia dicta.
                                <p>
                                    <a href="article.html" class="btn btn-primary">Lire la suite</a>
                                </p>
                            </div>
                        </div>
                    </article>                    
                </div>
                <!--Begin Pagination-->
                <nav>
                    <ul class="pagination justify-content-center">
                        <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
                        <li class="page-item active"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                    </ul>
                </nav>
                <!--End Pagination-->
            </div>
            <div class="col-12 col-md-3">
                <section class="card">
                    <div class="card-header bg-primary text-white">
                        <h1 class="h5">Catégories</h1>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <a href="#">Catégorie 1</a>
                            <span class="badge bg-primary rounded-pill">3</span>
                        </li>
                        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <a href="#">Catégorie 2</a>
                            <span class="badge bg-primary rounded-pill">10</span>
                        </li>
                        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <a href="#">Catégorie 3</a>
                            <span class="badge bg-primary rounded-pill">7</span>
                        </li>
                        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <a href="#">Catégorie 4</a>
                            <span class="badge bg-primary rounded-pill">12</span>
                        </li>
                        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <a href="#">Catégorie 5</a>
                            <span class="badge bg-primary rounded-pill">8</span>
                        </li>
                    </ul>
                </section>
            </div>
        </section>
    </div>
</body>
</html>
