<!-- PAGE HEADER -->
<div class="page_header">
    <div class="container">
        <div class="page_header_info text-center ">
            <div class="page_header_info_inner">
                <h2><?php echo $categorie['titre'] ?></h2>

            </div>
        </div>
    </div>
</div>

<div class="featured-products">
    <div class="container">
        <div class="row">
            <h5 class="heading"><span></span></h5>

            <div id="isotope" class="isotope">

                
                    <div class="isotope-item">
                        <div class="product-item">                           
                            <div class="product-info">
                                <h4 class="product-title"><a href="index.php?action=categorie&id=<?php echo $categorie['id']; ?>"role="button"><?php echo $categorie['titre']; ?></a></h4>    

                            </div>
                        </div>
                    </div>
               
            </div>
        </div>
    </div>
</div>
<div class="clearfix space20"></div>