<div class="container d-flex justify-content-center">
    <div class="col-md-6 col-sm-12">
        <h1 class="text-center">Accéder au changement</h1>
        <h3 class="text-center">Veuillez cliquer sur le lien ci-dessous</h3>
        <h4 class="text-center">pour modifier le mot de passe</h4>
        <div class="text-center">
            <a href="index.php?action=recover&u=<?= base64_encode($token_user) . '&token=' . base64_encode($token) ?>"
                class="btn btn-primary">Lien du changement</a>
        </div>
    </div>
</div>