<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="./view/asset/js/bootstrap.bundle.min.js"></script>
    <script src="./view/asset/js/toast.js"></script>
    <link rel="stylesheet" href="./view/asset/css/index.css">
    <link rel="stylesheet" href="./view/asset/css/login.css">
    <link rel="stylesheet" href="./view/asset/css/bootstrap.min.css">        
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="./view/asset/js/inscription.js"></script>

<title>Document</title>
</head>
<body>
<header class="navbar navbar-expand-md navbar-light bg-light px-3">
    <a href="index.php" class="navbar-brand">
        <h3>Parent-Eleves Veyre-Monton</h3>
    </a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar-content">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-content">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link bg-primary text-white rounded m-2" href="index.php">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link bg-primary text-white rounded m-2" href="index.php?action=articleAll">Nos Articles</a>
            </li>
            <!-- <li class="nav-item"> 
              <a class="nav-link bg-primary text-white rounded m-2" href="#">Nos Produits</a>
             </li>
            <li class="nav-item">
              <a class="nav-link bg-primary text-white rounded m-2" href="#">Les Menus (Cantine)</a>
             </li> -->
        </ul>
        <ul class="navbar-nav">
        <?php if (isset($_SESSION['login_nom'])) { ?>
            <li class="nav-item">
                <div class="tbr-info">
                    <span class="nav-link bg-primary text-white rounded m-1">Bonjour,
                      <?php echo $_SESSION['login_nom']; ?>
                    </span>
                </div>
            </li>
            <li class="nav-item">
                <div class="tbr-info">
                    <a href="index.php?action=monCompte" class="nav-link bg-dark text-white rounded m-1">Mon Compte</a>
                </div>
            </li>
            <li class="nav-item">
                <div class="tbr-info">
                    <a href="index.php?action=deconnexion" class="nav-link bg-dark text-white rounded m-1">Déconnexion</a>
                </div>
            </li>
        <?php } else { ?>
            <li class="nav-item">
                <div class="tbr-info">
                    <a href="index.php?action=login" class="nav-link bg-primary text-white rounded"> Connexion / Inscription</a>
                </div>
            </li>
        <?php } ?>
        </ul>
    </div>
</header>

<script src="./view/asset/js/inscription.js"></script>
        </body>