

        <!-- BREADCRUMBS -->
<div class="bcrumbs">
      <div class="container">
          <ul>
              <li><a href="index.php?action=index">Acceuil</a></li>
              <li><a href="index.php?action=index">Produit</a></li>
              <li>Fiche Produit</li>
          </ul>
      </div>
  </div>

  

                  <div class="clearfix space40"></div>
                  <div class="row">
                      <div class="col-md-12 col-sm-12">
                          <h5 class="heading space40"><span>Articles</span></h5>
                          <div class="product-carousel3">

                          <section class="row gy-3">
            <?php foreach($listearticle as $at) { ?>
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card">
                    <img src="<?php echo $at['image'] ?>'" alt="Coding" class="card-img-top">
                    <div class="card-body">
                        <h1 class="h3 card-title"><?php echo $at['titre'] ?></h1>
                        <p class="card-text"><?php echo $at['paragraphe'] ?></p>
                        <a href="index.php?action=article&id=<?= $at['id'];?>" class="btn btn-primary">Lire la suite</a>
                    </div>
                </div>
            </div>
            
            
            <?php } ?>
        </section>

                              
                                  

                             

                          </div>
                      </div>
                  </div>
                  <div class="clearfix space20"></div>

              </div>
          </div>
      </div>
  </div>

  <div class="clearfix space20"></div>

  <!-- FOOTER -->