<!doctype html>
<html lang="fr">

<head>
  <title>Réinitialiser mon mot de passe</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
</head>

<body>
  <div class="container">
    <div class="col-11">
      <div class="card text-center m-4 shadow p-3 mb-5 bg-white rounded">
        <div class="card-body">
          <h4 class="card-title p-3">Réinitialiser mon mot de passe</h4>
          <div class="form-group">
            <form action="index.php?action=password_change_post" method="POST" id="formInscription">
            <!-- Cette ligne de code crée un champ de formulaire HTML de type "hidden" qui stocke la valeur du token passé en paramètre via la méthode GET.

Plus précisément, la fonction PHP "htmlspecialchars" est utilisée pour convertir les caractères spéciaux en entités HTML, évitant ainsi les problèmes de sécurité liés aux attaques XSS. Ensuite, la fonction "base64_decode" est utilisée pour décoder la chaîne de caractères encodée en base64 pour récupérer la valeur du token. Cette valeur est ensuite insérée dans la valeur de l'attribut "value" du champ de formulaire.

Le champ de formulaire "hidden" est utilisé pour stocker des valeurs qui ne doivent pas être modifiées par l'utilisateur mais qui doivent être envoyées avec la soumission du formulaire. Ici, le token est un identifiant unique qui permet d'identifier l'utilisateur qui souhaite modifier son mot de passe et qui est nécessaire pour exécuter la requête SQL de mise à jour. -->
              <input type="hidden" name="token" value="<?php echo base64_decode(htmlspecialchars($_GET['u'])); ?>" />
              <input type="password" id="password" name="password" class="form-control" placeholder="Mot de passe"
                required />
              <br />
              <input type="password" id="password_repeat" name="password_repeat" class="form-control"
                placeholder="Re-tapez le mot de passe" required />
              <button type="submit" class="btn btn-primary btn-lg m-3" name="inscription"
                id="inscription">Modifier</button>
                <p class="bg-success" id="message"></p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
 <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
  crossorigin="anonymous"></script>
<script src="./view/asset/js/password_change.js"></script>


</body>

</html>